### ISSUE TITLE
Debug level

### ISSUE THREAD

**Issue by julianofischer** [akeranen/the-one#1]
Suggestion:

When running MaxPropRouter, there is a snippet of code frequently called (from routing.maxprop.MeetingProbability, which prints some information in output stream.

```java
if (probs.size() >= maxSetSize) {
            core.Debug.p("Probsize: " + probs.size() + " dropping " +
                    probs.remove(smallestEntry.getKey()));

        }
}
```
It is frequently annoying and could lead to performance degradation.
Perhaps the best default option for debugging is not debugging, actually.

Actually, in my code I changed the snippet in order to workaround:

```java
if (probs.size() >= maxSetSize) {
            probs.remove(smallestEntry.getKey()));
            //core.Debug.p("Probsize: " + probs.size() + " dropping " +
           //         probs.remove(smallestEntry.getKey()));

        }
}
```
It would be nice a (not hardcoded) way to disable it (increase the debug level).
I could contribute with a pull request if the authors agree to reade the debug level from settings:

        Debug.level = x

**Comment by tk721** [comment]
One, somewhat orthogonal thing would be to guard the debug logging statements with a global `static final DEBUG_BUILD` if-statement. For production, compiling with `DEBUG_BUILD = false` would cause the debug logging statements to be stripped out.

**Comment by julianofischer** [comment]
I believe @tk721's idea will lead to a better performance since the "undesired" code will be removed from bytecode due to compiler optimization. Since performance matters, I think it is better choice than the one I myself suggested, so +1 for Teemu's suggestion.

**Comment by barun-saha** [comment]
This would be a nice feature. In addition to what @julianofischer and @tk721 have already mentioned, perhaps we can have different levels of information emission, such as `INFO`, `DEBUG`, and `ERROR`, which are commonly used by many software. However, an important consideration would be the volume of information that the simulator emit as a whole.

**Comment by akeranen** [comment]
+1 for @tk721's idea. There is already support for different debug levels at the core/Debug.java, but apparently I forgot to define the constants for them. Should fix it.
