### ISSUE TITLE
Interface namespace returns different results

### ISSUE THREAD

**Issue by ili-fl7** [akeranen/the-one#101]
In two almost identical configuration files, the only difference is the namespace for the defined interface. One configuration uses the default name (as declared in default config file "btInterface") while the other one uses another random namespace (in this case "blInterface"). These two interfaces have everything else in common (i.e. type, range, and speed). However they achieve different results in the report file created using "MessageStatsReport" module.
Experiments have been done to validate this issue in different forms. Different random namespaces as well as different range and speed values have been taken into consideration during the experiments. 
The overall result was that when using "btInterface" namespace, results would be different from any other namespace. This is while for the rest of the random namespaces results are consistently the same with resect to the same type, range, and speed.
Two configuration files as well as their corresponding report files are attached who have literally everything in common except the interface namespace. It must be noted that I am using a custom mobility model.

[Config_blInterface.txt](https://github.com/akeranen/the-one/files/7048136/Config_blInterface.txt)
[Config_btInterface.txt](https://github.com/akeranen/the-one/files/7048137/Config_btInterface.txt)
[report_blInterface.txt](https://github.com/akeranen/the-one/files/7048138/report_blInterface.txt)
[report_btInterface.txt](https://github.com/akeranen/the-one/files/7048139/report_btInterface.txt)

**Comment by julianofischer** [comment]
Hey @ili-fl7 how are you?
That is my guess.
Whenever a 'default_settings.txt' file is in the root dir, it is read by ONE and their values are put in the simulation.
When you use any name which is not "btInterface" values are not override.
However, if the interface name is 'btInterface' configurations may be overridden.
I am not sure if that is the way that settings are working since I am some years away from ONE, however, a very simple way to test it is to remove "default_settings.txt" from ONE's dir.

**Comment by ili-fl7** [comment]
Hey @julianofischer,
good, what about you?
Thanks for your reply. There were indeed some values that were not overridden.
I am getting constant results as I removed the default settings from the root directory.
Thanks for the guidance.

**Comment by julianofischer** [comment]
@ili-fl7 I'm good, thank you!
I'm glad to have helped.
