### ISSUE TITLE
Node movement accessing position of other nodes?

### ISSUE THREAD

**Issue by j4cobgarby** [akeranen/the-one#105]
Hi, not an issue as such but I'm hoping this may be the right place to ask questions,
I want to write a movement model where the path each node takes is dependent on the positions of other nodes around it, and so for this I need to somehow access the World from an instance of a MovementModel. Is there some way to achieve this?
Many thanks

**Comment by akeranen** [comment]
Best place for asking questions is [StackOverflow](https://stackoverflow.com/questions/tagged/one-simulator) with tag "one-simulator".

Github issues are best for things that can be addressed with a PR (bugs, new features, etc.).
