### ISSUE TITLE
About sendQueue configuration

### ISSUE THREAD

**Issue by julianofischer** [akeranen/the-one#14]
I know we are all consenting adults here, but I really think it would be easier to understand, particularly for beginners, the use of names to configure sendQueue.

Thus,
FIFO
fifo
FiFO
fIFO
...
would be mapped to 2

and Random (and variations) would be mapped to 1.

It is a cosmetic modification but I think it would improve the user experience.

**Comment by tk721** [comment]
Merged to master.
