### ISSUE TITLE
GUI crashes if node has no interface

### ISSUE THREAD

**Issue by tk721** [akeranen/the-one#2]
The simulation GUI crashes if a node has no interface specified.

```
Exception in thread "AWT-EventQueue-0" core.SimError: No such interface: 1 at x0
	at core.DTNHost.getInterface(DTNHost.java:269)
	at core.DTNHost.isRadioActive(DTNHost.java:122)
	at gui.playfield.NodeGraphic.drawHost(NodeGraphic.java:71)
	at gui.playfield.NodeGraphic.draw(NodeGraphic.java:47)
	at gui.playfield.PlayField.paint(PlayField.java:195)
```

## Minimal configuration to reproduce:

```
Scenario.name = MyScenario
Scenario.endTime = 600
Scenario.updateInterval = 0.1
Scenario.simulateConnections = false
MovementModel.worldSize = 1000,1000
Report.nrofReports = 0
Events.nrof = 0
Scenario.nrofHostGroups = 1
Group1.groupID = x
Group1.nrofHosts = 1
Group1.nrofInterfaces = 0
Group1.movementModel = RandomWalk
Group1.router = PassiveRouter
```

## Expected behavior:

The node is drawn without a radio range, or exception is thrown before launching the simulation.

**Comment by akeranen** [comment]
I wonder if there is any use case for a node without an interface. If yes, "drawn without radio range" sounds like a good idea.

**Comment by tk721** [comment]
There is when doing only mobility simulations. Looking into things like flight lengths and resulting node densities in the simulation area, rather than connectivity.
