### ISSUE TITLE
unzip on win10 issue

### ISSUE THREAD

**Issue by ak34a** [akeranen/the-one#22]
Hello,
I downloaded the The ONE v1.6.0 on my win10 laptop. for some reason is it not able to unzip the files! also i have tried to download the old  1.4 version and there is issues with the compiling and when i doe compile. bat on the CLI, it just dissapears without starting the ONE platform! , it keep saying could not find the file ! i have followed all the steps for downloading. please need help with that. thanks

**Comment by akeranen** [comment]
I tested the zip file on Mac OS X and Windows and it seems to work fine. Did you use the link on the github pages (https://github.com/akeranen/the-one/zipball/master)?

compile.bat just compiles ONE; one.bat is used to start the program.

**Comment by johnny-jiang** [comment]
It looks like that you have not install JDK or add it to the PATH. So when you run compile.bat it said could not find the file. Please check what it said ,maybe it can't find javac.exe. You can try to run command 'javac' and 'java' in CMD to test if your JDK is working.
