### ISSUE TITLE
how to transfer GPS trace to the format The ONE can process?

### ISSUE THREAD

**Issue by layrong** [akeranen/the-one#28]
how to transfer GPS trace to the format The ONE can process? such as follows:
351;2014-02-01 00:00:04.487352+01;POINT(41.9100508227258 12.4966092132391)
thanks for answer

**Comment by tk721** [comment]
GPS coordinates are spherical and the ONE coordinates are rectangular. Hence you need to do a map projection of your trace onto a plane. That must done externally from the ONE.

**Comment by julianofischer** [comment]
I suggest GeoPy.

https://github.com/geopy/geopy
