### ISSUE TITLE
MovementListener.initialLocation() does not get called

### ISSUE THREAD

**Issue by tk721** [akeranen/the-one#3]
`MovementListener.initialLocation()` never gets called.

The reason seems to be that the listeners are invoked in the `DTNHost` constructor, but at that time the report modules have not yet been created so there are no listeners to invoke (see `DTNSimUI.initModel()`).

## Reproducing

1. Create a new `Report` subclass that implements `MovementListener`.
2. Add an implementation of `initialLocation()`.
3. Observe that the implementation is never reached (e.g., break point or debug printing).

**Comment by akeranen** [comment]
Solution: remove initialLocation method from MovementListener interface?

**Comment by tk721** [comment]
That would mean that there is no way to get the first path followed by every node in the simulation. Better solution would be to instantiate the report modules before instantiating the DTNHosts, but that might break something.
