### ISSUE TITLE
Support kiB, MiB and GiB as data units

### ISSUE THREAD

**Issue by julianofischer** [akeranen/the-one#4]
1. It is an enhancement.
2. It is more cosmetic than it is functional.
3. As a consequence of 1 and 2, it may have a low priority (if accepted).

Add support to kibibytes (1024 bytes), mebibyte (2^20 bytes), gibibyte (2^30 bytes) as information units.
The suffixes could be KiB, MiB, and GiB.

Another  nice feature would be StandardEventsReader supporting the new and already existing units (k, M and G).

Examples:

    10 C 1 4 6 1k

would create a message with 1000 bytes.

    10 C 1 4 6 1kiB

would create a message with 1024 bytes.

**Comment by akeranen** [comment]
I think this is a reasonable addition. Would you like to propose code for the fix?

**Comment by julianofischer** [comment]
I think for the second feature it is needed modify only the StandardEventsReader class, what would be easy. However, I am not sure in how to support the new data units in settings nor if the modifications have implications for the GUI since I do not use it frequently. Anyway, if a delay is tolerated (pardon the pun), I would appreciate to propose a fix suggestion.

**Comment by akeranen** [comment]
For the settings I think updating the parseDouble method would be enough. IIRC, the GUI does not use k/M/G at all, so it should not be affected. And take your time, that should not be a problem.
