### ISSUE TITLE
Why the PROPHETrouter GAMMA is  static

### ISSUE THREAD

**Issue by 627850449** [akeranen/the-one#49]
Why the PROPHETrouter GAMMA is  static?
Why 0.98?
my opinion is that it is related to the speed of hosts.
I think GAMMA is a variable.

**Comment by julianofischer** [comment]
Probably the value was extracted from the paper.
According to Lindgren et al.:
> "preliminary simulations indicated those values were reasonable choices for the parameters"

Anyway, I agree it could be a variable value. It is a modification easy to be made in backward mode.
Let's wait for the opinion of @akeranen and @tk721.

**Comment by akeranen** [comment]
Yes, when implementing this routing module, I just followed what was described in the paper. For further experimentation having it configurable sounds reasonable.

**Comment by 627850449** [comment]
I think the GAMMA is related to the speed of hosts. And the experiment showed that when the speed became higher, the best GAMMA should be bigger.
