### ISSUE TITLE
undesirable behavior

### ISSUE THREAD

**Issue by julianofischer** [akeranen/the-one#60]
Hi guys, how are you?

We have an undersirable problem regarding to the TTL calculation:

    public int getTtl() {
    		    if (this.initTtl == INFINITE_TTL) {
			    return Integer.MAX_VALUE;
		    }
		    else {
			    return (int)( ((this.initTtl * 60) -
					    (SimClock.getTime()-this.timeCreated)) /60.0 );
		    }
    }

When a user enter a value greater than Integer.MAX_VALUE/60 occurs an integer overflow which results in negative values for TTL.

A possible workaround is to limit ttl maximum value to 35,791,394 which works fine.
35,791,395 leads to a negative value.

**Comment by akeranen** [comment]
Good catch. Throwing SettingsError with too large TTL values sounds like a good remedy.

**Comment by vicaba** [comment]
Btw, no one is merging those changes, right?
