### ISSUE TITLE
MaxPropRouter causes "java.lang.OutOfMemoryError: GC overhead limit exceeded"

### ISSUE THREAD

**Issue by aunroel** [akeranen/the-one#66]
I have encountered an issue when running simulations for MaxPropRouter with 500 nodes in the simulator for 21600s or more. The simulation runs for a couple of seconds and then causes following error:
<img width="1054" alt="screen shot 2018-03-30 at 01 36 31" src="https://user-images.githubusercontent.com/12754142/38119642-3a074280-33bb-11e8-9542-a4a414ef851b.png">

Simulator was able to run MaxPropRouter simulations with 100 nodes over 10800s (3h) , 21600s (6h) and 43200s (12h). I use MapBasedMovement and ShortesPathMapBasedMovement as moving models and **MaxPropRouter.probSetMaxSize = 15** as only setting for this router model.

I have tried increasing the JVM memory to 1G in "java -Xmx1024M -cp target:lib/ECLA.jar:lib/DTNConsoleConnection.jar core.DTNSim $*", but the result was the same. Neither did affect anything changing the value of probSetMaxSize in range from 5 to 50.

Simulator works fine for the rest of the protocols (Epidemic, Prophet, etc.).

At this point I have no idea how to address this problem.

P.S. simulations executed on Mac OS and Linux.

**Comment by julianofischer** [comment]
Please, consider try:
-Xms512m
-Xmx1024m

**Comment by aunroel** [comment]
I did try "java -Xmx1024M ..." , but it didn't help

**Comment by akeranen** [comment]
As @julianofischer mentioned, seems that your VM is running out of memory. Either your simulating machine runs out of memory or there's something wrong in the Java VM configuration. But it doesn't seem to be a problem with the simulator itself, so I'll close this issue.
