### ISSUE TITLE
problem with compiling the .bat files

### ISSUE THREAD

**Issue by anikaaziz** [akeranen/the-one#72]
Hi! I will really appreciate your help in solving the following problem:
After downloading the ONE 1.6.0 , when I tried compile.bat and one.bat commands from the command prompt got the following error messages-(jdk10.0.1 and jre 10.0.1 are successfully installed and tested in the computer)
1.
H:\the-one-1.6.0>compile.bat

H:\the-one-1.6.0>javac -extdirs lib/ core/*.java
javac: option -extdirs not allowed with target 1.10

H:\the-one-1.6.0>javac -extdirs lib/ movement/*.java
javac: option -extdirs not allowed with target 1.10
............
2.
H:\the-one-1.6.0>one.bat

H:\the-one-1.6.0>java -Xmx512M -cp .;lib/ECLA.jar;lib/DTNConsoleConnection.jar core.DTNSim
Error: Could not find or load main class core.DTNSim
Caused by: java.lang.ClassNotFoundException: core.DTNSim
Thanks in advance.
-Anika

**Comment by warlead77** [comment]
i also have the same problem here
