### ISSUE TITLE
javac: option -extdirs not allowed with target 1.10

### ISSUE THREAD

**Issue by bhskr44** [akeranen/the-one#74]
I am unable to compile using sh compile.sh in my ubuntu 18.04

**Comment by julianofischer** [comment]
What Java version are you using?
Put the error message here, please.

**Comment by bhskr44** [comment]
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.2, mixed mode)


Erron message : javac: option -extdirs not allowed with target 1.10

**Comment by julianofischer** [comment]
It is because extedirs is not present in the java version you use.
try changing -extdirs to -cp

**Comment by bhskr44** [comment]
changing to -cp leaves to 31 errors

Error Message:
src/core/DTN2Manager.java:20: error: package fi.tkk.netlab.dtn.ecla does not exist
import fi.tkk.netlab.dtn.ecla.Bundle;
                             ^
src/core/DTN2Manager.java:21: error: package fi.tkk.netlab.dtn.ecla does not exist
import fi.tkk.netlab.dtn.ecla.CLAParser;
                             ^
src/core/DTN2Manager.java:32: error: cannot find symbol
	private static Map<DTNHost, CLAParser>	CLAs = null;
	                            ^
  symbol:   class CLAParser
  location: class DTN2Manager
src/core/DTN2Manager.java:36: error: cannot find symbol
	private static Map<String, Bundle>		bundles = null;
	                           ^
  symbol:   class Bundle
  location: class DTN2Manager
src/report/DTN2Reporter.java:12: error: package fi.tkk.netlab.dtn.ecla does not exist
import fi.tkk.netlab.dtn.ecla.CLAParser;
                             ^
src/input/DTN2Events.java:8: error: package fi.tkk.netlab.dtn does not exist
import fi.tkk.netlab.dtn.DTNConsoleConnection;
                        ^
src/input/DTN2Events.java:9: error: package fi.tkk.netlab.dtn.ecla does not exist
import fi.tkk.netlab.dtn.ecla.Bundle;
                             ^
src/input/DTN2Events.java:10: error: package fi.tkk.netlab.dtn.ecla does not exist
import fi.tkk.netlab.dtn.ecla.CLAInterface;
                             ^
src/input/DTN2Events.java:11: error: package fi.tkk.netlab.dtn.ecla does not exist
import fi.tkk.netlab.dtn.ecla.CLAParser;
                             ^
src/core/DTN2Manager.java:189: error: cannot find symbol
	public static CLAParser getParser(DTNHost host) {
	              ^
  symbol:   class CLAParser
  location: class DTN2Manager
src/core/DTN2Manager.java:212: error: cannot find symbol
	public static void addBundle(String id, Bundle bundle) {
	                                        ^
  symbol:   class Bundle
  location: class DTN2Manager
src/core/DTN2Manager.java:221: error: cannot find symbol
	public static Bundle getBundle(String id) {
	              ^
  symbol:   class Bundle
  location: class DTN2Manager
src/input/DTN2Events.java:44: error: cannot find symbol
	private Map<String, Bundle>			bundle_list;
	                    ^
  symbol:   class Bundle
  location: class DTN2Events
src/input/DTN2Events.java:66: error: cannot find symbol
	public class ParserHandler implements CLAInterface {
	                                      ^
  symbol:   class CLAInterface
  location: class DTN2Events
src/input/DTN2Events.java:230: error: cannot find symbol
	private void enqueMsg(int from, int to, Bundle bundle) {
	                                        ^
  symbol:   class Bundle
  location: class DTN2Events
src/input/DTN2Events.java:243: error: cannot find symbol
	private void regMsg(Bundle bundle) {
	                    ^
  symbol:   class Bundle
  location: class DTN2Events
src/input/DTN2Events.java:251: error: cannot find symbol
	private boolean isReg(Bundle bundle) {
	                      ^
  symbol:   class Bundle
  location: class DTN2Events
src/input/DTN2Events.java:71: error: cannot find symbol
		private DTNConsoleConnection	console;
		        ^
  symbol:   class DTNConsoleConnection
  location: class DTN2Events.ParserHandler
src/input/DTN2Events.java:92: error: package CLAParser does not exist
				CLAParser.BundleAttributes attributes) {
				         ^
src/input/DTN2Events.java:91: error: cannot find symbol
		public BundleTransferReceipt incomingBundle(String location,
		       ^
  symbol:   class BundleTransferReceipt
  location: class DTN2Events.ParserHandler
src/core/DTN2Manager.java:71: error: cannot find symbol
		DTN2Manager.CLAs = new HashMap<DTNHost, CLAParser>();
		                                        ^
  symbol:   class CLAParser
  location: class DTN2Manager
src/core/DTN2Manager.java:73: error: cannot find symbol
		DTN2Manager.bundles = new HashMap<String, Bundle>();
		                                          ^
  symbol:   class Bundle
  location: class DTN2Manager
src/core/DTN2Manager.java:129: error: cannot find symbol
				CLAParser p;
				^
  symbol:   class CLAParser
  location: class DTN2Manager
src/core/DTN2Manager.java:130: error: cannot find symbol
				p = new CLAParser(dtnd_host, dtnd_port, "ONE");
				        ^
  symbol:   class CLAParser
  location: class DTN2Manager
src/report/DTN2Reporter.java:74: error: cannot find symbol
			CLAParser p = DTN2Manager.getParser(to);
			^
  symbol:   class CLAParser
  location: class DTN2Reporter
src/input/DTN2Events.java:52: error: cannot find symbol
		this.bundle_list = new HashMap<String, Bundle>();
		                                       ^
  symbol:   class Bundle
  location: class DTN2Events
src/input/DTN2Events.java:95: error: package CLAInterface does not exist
			CLAInterface.BundleTransferReceipt r =
			            ^
src/input/DTN2Events.java:96: error: package CLAInterface does not exist
				new CLAInterface.BundleTransferReceipt();
				                ^
src/input/DTN2Events.java:129: error: cannot find symbol
			Bundle bundle = new Bundle(new_f);
			^
  symbol:   class Bundle
  location: class DTN2Events.ParserHandler
src/input/DTN2Events.java:129: error: cannot find symbol
			Bundle bundle = new Bundle(new_f);
			                    ^
  symbol:   class Bundle
  location: class DTN2Events.ParserHandler
src/input/DTN2Events.java:169: error: cannot find symbol
			this.console = new DTNConsoleConnection(this.c_host, this.c_port);
			                   ^
  symbol:   class DTNConsoleConnection
  location: class DTN2Events.ParserHandler
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
31 errors

**Comment by bhskr44** [comment]
Thanks, it worked for me as well.

**Comment by evie5** [comment]
> I changed as the following an it worked for me.
> 
> ```
> targetdir=target
> 
> if [ ! -d "$targetdir" ]; then mkdir $targetdir; fi
> 
> javac -sourcepath src -d $targetdir -cp lib/ECLA.jar:lib/DTNConsoleConnection.jar src/core/*.java src/movement/*.java src/report/*.java src/routing/*.java src/gui/*.java src/input/*.java src/applications/*.java src/interfaces/*.java
> 
> if [ ! -d "$targetdir/gui/buttonGraphics" ]; then cp -R src/gui/buttonGraphics target/gui/; fi
> ```

Hello @julianofischer !

I hope you're doing fine.
I have a question for you please, I would like to know where did you made those changes?
I'm a newbie, sorry for the lame question :)

**Comment by julianofischer** [comment]
@evie5 sorry the late response.
The changes must be made to the compile.sh file

**Comment by michaelgreyskull** [comment]
I know this is an old and closed issue but does anyone know how to fix this for Windows?

When changing -extdirs to -cp I get exactly these 31 errors bhskr44 pointed out. As far as I can see, my .bat file does the same as the fixed .sh file.
But I cannot find out what exactly is the difference. Here is the contents of the .bat file:

```
set targetdir=target
IF NOT EXIST "%targetdir%" mkdir %targetdir%

javac -sourcepath src -d $targetdir -cp lib/ECLA.jar:lib/DTNConsoleConnection.jar src/core/*.java src/movement/*.java src/report/*.java src/routing/*.java src/gui/*.java src/input/*.java src/applications/*.java src/interfaces/*.java

IF NOT EXIST "%targetdir%\gui\buttonGraphics" (
	mkdir %targetdir%\gui\buttonGraphics
	copy src\gui\buttonGraphics\* %targetdir%\gui\buttonGraphics\
)
```

**Comment by SaltyHash123** [comment]
Try this one (seems that the syntax for the separation of the .jar files is different in Windows)

```
set targetdir=target

IF NOT EXIST "%targetdir%" mkdir %targetdir%

javac -sourcepath src -d %targetdir% -cp lib/ECLA.jar;lib/DTNConsoleConnection.jar; src/core/*.java src/movement/*.java src/report/*.java src/routing/*.java src/gui/*.java src/input/*.java src/applications/*.java src/interfaces/*.java



IF NOT EXIST "%targetdir%\gui\buttonGraphics" (
	mkdir %targetdir%\gui\buttonGraphics
	copy src\gui\buttonGraphics\* %targetdir%\gui\buttonGraphics\
)
```
