### ISSUE TITLE
getInterface(interfaceNo) starts at 1

### ISSUE THREAD

**Issue by Lithimlin** [akeranen/the-one#88]
So, why does the counter for interfaces of the DTNHost getter `getInterface(int interfaceNo)` start at 1?
This is super confusing and lead to quite a few errors for me already. Where was this used so far?

**Comment by akeranen** [comment]
Don’t quite remember the rationale anymore, but the reason might have been to save the index 0 for special cases. But would be a bit too late to change that now.
